title: Ryan Ellison's website
description: Redesign in progress
theme: just-the-docs

url: https://RyanJ-Ellison.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

search_enabled: true
logo: "/assets/images/Picture_Me.jpg"
ga_tracking: G-X7P50197W6
ga_tracking_anonymize_ip: true
footer_content: Twitter @_Ryan_Ellison , [LinkedIn](https://www.linkedin.com/in/ryan-ellison-b5b7b4159/)