title: Ryan Ellison
logo: /assets/img/Picture_Me.JPG

twitter: https://twitter.com/_Ryan_Ellison
linkedin: https://www.linkedin.com/in/ryan-ellison-b5b7b4159/
#github: https://github.com/vladUng
description: Ryan Ellison's Website
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

gems:
  - jemoji