title: Ryan Ellison's website
description: Redesign in progress
theme: just-the-docs

url: https://RyanJ-Ellison.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
